### ISSUE TITLE
Standalone tooltips added to React-Joyride 1.0

### ISSUE THREAD

**Issue by gilbarbara** [jmrog/react-tooltipper#7]
Let me know if these new options can help you!
[v1.0](https://github.com/gilbarbara/react-joyride/releases/tag/1.0.0)

**Comment by jmrog** [comment]
@gilbarbara Very cool! I didn't know this was on your roadmap! I'll definitely check it out when I get the chance. Maybe it'll even make this fork obsolete. :)

**Comment by jmrog** [comment]
Oh, and congrats on the 1.0 release. Looks like some pretty big changes there, especially with the refactoring to a component (which I like a lot!).

**Comment by gilbarbara** [comment]
@jmrog Yay, thanks!
I've never liked the mixin approach but I needed the functionality in a hurry for a project so I ended up building it like that. I think this new version is a big improvement!
If you have any other suggestions or requests let me know!

:+1:
