### ISSUE TITLE
How to use in react-tooltipper with ES6 class?

### ISSUE THREAD

**Issue by kokill** [jmrog/react-tooltipper#9]
i cannot use mixin in ES6 class, so how to use `this.tooltipperSetTooltipData,` and `this.tooltipperTrigger` with ES6 class in React.

**Comment by jmrog** [comment]
Hi @kokill, I'm sorry that it's taken me so long to respond to this. To use this sort of tool with ES6, you really should just switch to [react-joyride](https://github.com/gilbarbara/react-joyride). This project was originally a fork of that project for an internal reason (which I don't remember anymore), and it isn't really maintained at this point; it's very out of date. I've added a deprecation notice to the README and have also now deprecated the package on npm to reflect this.

I hope that helps! If I can help in some other way, please let me know.
